package dev.lokeshbisht.intent_service.enums;

public enum ErrorCodes {

    INVALID_HEADERS,
    INT_SER_BAD_REQUEST,
    INT_SER_FORBIDDEN,
    MALFORMED_REQUEST_BODY,
    INT_SER_INTENT_NOT_FOUND,
    INT_SER_INTENT_ALREADY_EXISTS,
    INT_SER_INTERNAL_SERVER_ERROR,
    INT_SER_UNSUPPORTED_PAYMENT_TYPE
}
